apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redispubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@localhost:5672"
  - name: durable
    value: "true"
  - name: autoAck
    value: "false"
